/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package laboratorioprogramacion5;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Brayan_Pinel_Juego extends javax.swing.JFrame {
private String[] palabras = {"HONDURAS", "MANZANA", "COMIDA", "PROGRAMAR", "PERRO", "CUADERNO", "FACEBOOK", "PIZZA", "BRAYAN", "LIBRO"};
    private String palabraSeleccionada;
    private StringBuilder palabraEscondida;
    private int oportunidades;
    /**
     * Creates new form Brayan_Pinel_Juego
     */
    public Brayan_Pinel_Juego() {
        initComponents();
   
    panelMenu.setVisible(true);
        panelJuego.setVisible(false);
        panelCambiarPalabras.setVisible(false);
    

     

        
        
            // Inicializar juego
            Random random = new Random();
            palabraSeleccionada = palabras[random.nextInt(palabras.length)];
            palabraEscondida = new StringBuilder("_".repeat(palabraSeleccionada.length()));
            oportunidades = 5;

            botonPalabra.setText(palabraEscondida.toString());
            botonOportunidades.setText("Oportunidades: " + oportunidades);
            botonMensaje.setText("Adivina la palabra.");
    }
     
     
     
     
     
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        botonJugar = new javax.swing.JButton();
        botonCambiarPalabras = new javax.swing.JButton();
        panelJuego = new javax.swing.JPanel();
        botonEvaluar = new javax.swing.JButton();
        botonPalabra = new javax.swing.JLabel();
        botonLetra = new javax.swing.JTextField();
        botonOportunidades = new javax.swing.JLabel();
        botonMensaje = new javax.swing.JLabel();
        panelCambiarPalabras = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        botonLista = new javax.swing.JList<>();
        botonNuevaPalabra = new javax.swing.JTextField();
        botonAgregarPalabra = new javax.swing.JButton();
        botonEliminarPalabra = new javax.swing.JButton();
        botonVolverMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelMenu.setBorder(javax.swing.BorderFactory.createTitledBorder("El Menu"));

        botonJugar.setText("Jugar");
        botonJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonJugarActionPerformed(evt);
            }
        });

        botonCambiarPalabras.setText("Cambiar Palabra");
        botonCambiarPalabras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCambiarPalabrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(botonJugar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                .addComponent(botonCambiarPalabras)
                .addGap(26, 26, 26))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonJugar)
                    .addComponent(botonCambiarPalabras))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        panelJuego.setBorder(javax.swing.BorderFactory.createTitledBorder("Juego"));

        botonEvaluar.setText("Evaluar");
        botonEvaluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEvaluarActionPerformed(evt);
            }
        });

        botonLetra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLetraActionPerformed(evt);
            }
        });

        botonOportunidades.setText("jLabel3");

        botonMensaje.setText("jLabel3");

        javax.swing.GroupLayout panelJuegoLayout = new javax.swing.GroupLayout(panelJuego);
        panelJuego.setLayout(panelJuegoLayout);
        panelJuegoLayout.setHorizontalGroup(
            panelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJuegoLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(botonEvaluar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelJuegoLayout.createSequentialGroup()
                .addContainerGap(239, Short.MAX_VALUE)
                .addGroup(panelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelJuegoLayout.createSequentialGroup()
                        .addComponent(botonLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelJuegoLayout.createSequentialGroup()
                        .addComponent(botonMensaje)
                        .addGap(127, 127, 127))))
            .addGroup(panelJuegoLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(botonPalabra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonOportunidades)
                .addGap(127, 127, 127))
        );
        panelJuegoLayout.setVerticalGroup(
            panelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJuegoLayout.createSequentialGroup()
                .addGroup(panelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelJuegoLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(botonPalabra)
                        .addGap(44, 44, 44)
                        .addComponent(botonEvaluar))
                    .addGroup(panelJuegoLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(botonMensaje)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonLetra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonOportunidades)))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        panelCambiarPalabras.setBorder(javax.swing.BorderFactory.createTitledBorder("Cambair Palabras"));

        botonLista.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(botonLista);

        botonAgregarPalabra.setText("Agregar Palabra");
        botonAgregarPalabra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarPalabraActionPerformed(evt);
            }
        });

        botonEliminarPalabra.setText("Eliminar Palabra");
        botonEliminarPalabra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarPalabraActionPerformed(evt);
            }
        });

        botonVolverMenu.setText("Volver al Menu");
        botonVolverMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCambiarPalabrasLayout = new javax.swing.GroupLayout(panelCambiarPalabras);
        panelCambiarPalabras.setLayout(panelCambiarPalabrasLayout);
        panelCambiarPalabrasLayout.setHorizontalGroup(
            panelCambiarPalabrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCambiarPalabrasLayout.createSequentialGroup()
                .addGroup(panelCambiarPalabrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCambiarPalabrasLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(botonVolverMenu))
                    .addGroup(panelCambiarPalabrasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botonEliminarPalabra))
                    .addGroup(panelCambiarPalabrasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botonAgregarPalabra))
                    .addGroup(panelCambiarPalabrasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botonNuevaPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        panelCambiarPalabrasLayout.setVerticalGroup(
            panelCambiarPalabrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCambiarPalabrasLayout.createSequentialGroup()
                .addGroup(panelCambiarPalabrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCambiarPalabrasLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(botonVolverMenu))
                    .addGroup(panelCambiarPalabrasLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(botonNuevaPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonAgregarPalabra)
                .addGap(18, 18, 18)
                .addComponent(botonEliminarPalabra)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(178, 178, 178))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(panelJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelCambiarPalabras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelCambiarPalabras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonLetraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLetraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonLetraActionPerformed

    private void botonJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonJugarActionPerformed
 panelMenu.setVisible(false);
            panelJuego.setVisible(true);
            panelCambiarPalabras.setVisible(false);       
            
             Random random = new Random();
            palabraSeleccionada = palabras[random.nextInt(palabras.length)];
            palabraEscondida = new StringBuilder("_".repeat(palabraSeleccionada.length()));
            oportunidades = 5;

            botonPalabra.setText(palabraEscondida.toString());
            botonOportunidades.setText("Oportunidades: " + oportunidades);
            botonMensaje.setText("Adivina la palabra.");
    }//GEN-LAST:event_botonJugarActionPerformed

    private void botonAgregarPalabraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarPalabraActionPerformed

 String nuevaPalabra = botonNuevaPalabra.getText().toUpperCase();
            if (!nuevaPalabra.isEmpty()) {
                for (int i = 0; i < palabras.length; i++) {
                    if (palabras[i] == null) {
                        palabras[i] = nuevaPalabra;
                        botonLista.setListData(palabras);
                        botonNuevaPalabra.setText("");
                        return;
                    }
                }
                JOptionPane.showMessageDialog(this, "No se pueden agregar más palabras.");
            }

        // TODO add your handling code here:
    }//GEN-LAST:event_botonAgregarPalabraActionPerformed

    private void botonEvaluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEvaluarActionPerformed
 String letra = botonLetra.getText().toUpperCase();
            if (letra.length() == 1) {
                if (palabraSeleccionada.contains(letra)) {
                    botonMensaje.setText("¡Le pegaste a un carácter!");
                    for (int i = 0; i < palabraSeleccionada.length(); i++) {
                        if (palabraSeleccionada.charAt(i) == letra.charAt(0)) {
                            palabraEscondida.setCharAt(i, letra.charAt(0));
                        }
                    }
                    botonPalabra.setText(palabraEscondida.toString());
                    if (!palabraEscondida.toString().contains("_")) {
                        JOptionPane.showMessageDialog(this, "¡Felicidades, adivinaste la palabra!");
                        panelMenu.setVisible(true);
                        panelJuego.setVisible(false);
                    }
                } else {
                    oportunidades--;
                    botonMensaje.setText("No contiene ese carácter.");
                    botonOportunidades.setText("Oportunidades: " + oportunidades);
                    if (oportunidades == 0) {
                        JOptionPane.showMessageDialog(this, "¡Perdiste! La palabra era: " + palabraSeleccionada);
                        panelMenu.setVisible(true);
                        panelJuego.setVisible(false);
                    }
                }
            } else {
                botonMensaje.setText("Ingrese solo un carácter.");
            }
            botonLetra.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_botonEvaluarActionPerformed

    private void botonCambiarPalabrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCambiarPalabrasActionPerformed
 panelMenu.setVisible(false);
            panelJuego.setVisible(false);
            panelCambiarPalabras.setVisible(true);

            botonLista.setListData(palabras);
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCambiarPalabrasActionPerformed

    private void botonEliminarPalabraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarPalabraActionPerformed

 String seleccion = botonLista.getSelectedValue();
            if (seleccion != null) {
                for (int i = 0; i < palabras.length; i++) {
                    if (seleccion.equals(palabras[i])) {
                        palabras[i] = null;
                        botonLista.setListData(palabras);
                        return;
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Seleccione una palabra para borrar.");
            }
        // TODO add your handling code here:
    }//GEN-LAST:event_botonEliminarPalabraActionPerformed

    private void botonVolverMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverMenuActionPerformed

     panelMenu.setVisible(true);
            panelJuego.setVisible(false);
            panelCambiarPalabras.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_botonVolverMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Brayan_Pinel_Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Brayan_Pinel_Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Brayan_Pinel_Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Brayan_Pinel_Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Brayan_Pinel_Juego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarPalabra;
    private javax.swing.JButton botonCambiarPalabras;
    private javax.swing.JButton botonEliminarPalabra;
    private javax.swing.JButton botonEvaluar;
    private javax.swing.JButton botonJugar;
    private javax.swing.JTextField botonLetra;
    private javax.swing.JList<String> botonLista;
    private javax.swing.JLabel botonMensaje;
    private javax.swing.JTextField botonNuevaPalabra;
    private javax.swing.JLabel botonOportunidades;
    private javax.swing.JLabel botonPalabra;
    private javax.swing.JButton botonVolverMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelCambiarPalabras;
    private javax.swing.JPanel panelJuego;
    private javax.swing.JPanel panelMenu;
    // End of variables declaration//GEN-END:variables
}
